### ISSUE TITLE
Refactor: The 'drawerOpen' prop is an antipattern.

### ISSUE THREAD

**Issue by abrie** [webdevatlanta/GroupCollaborationTool#78]
The app has two render states; NavDrawer Open, and NavDrawer Closed. The state is communicated to components via a prop. Ideally this should be moved to a a context and have better inversion of control.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/1462268/73409903-9f357b80-42ce-11ea-9e04-9066a72d1c12.png">

**Comment by DanielJWagener** [comment]
Would fixing this issue also fix all the components re-rendering every time the drawer opens or closes? I was playing around with the app just now, and the projects table's re-rendering is kinda glaring. I couldn't figure out how to fix it though-- that problem is defying my understanding of how hooks work.
